this ticket has 2 mentioned use cases but only 1 is currently working…
triveni-codev/GBWebApp-dev pull request #430
Opened 2022-05-04 05:22 UTC by darlp5589

@chriscodev , kindly review this PR.

Here's the ASANA Link: https://app.asana.com/0/1201943683850147/1202187061972897

There are 2 mentioned use cases here but I want you to check only the first one since the other one is currently under development. 

Here's how you can test: 

1. Add a Logical Network -> Add a new ATSC Channel -> Make inputs/changes -> OK -> Update the same ATSC Channel -> Make modifications → OK

2022-05-05 00:49 UTC, chriscodev requested changes
- remove console logs

- remove commented lines of code

- on add  atsc services table gets destroyed, it should not be destroyed on adding channel settings

![crop](https://user-images.githubusercontent.com/68254582/166849369-6b4dc2ac-b845-4497-9b1d-35533185a6d2.jpg)

2022-05-05 00:49 UTC, chriscodev commented on src/app/pages/dashboard/network-config/networks/modal-networks/modal-networks-atsc-channel/modal-networks-atsc-channel.component.ts
> +		console.log("constructor for Channel: ",this.modalChannelData)
remove console.log

2022-05-05 00:49 UTC, chriscodev commented on src/app/pages/dashboard/network-config/networks/networks.component.ts
> +			//if($event.hasOwnProperty('modulation')) this.channelChangedHandler($event);
remove commented code

2022-05-05 07:06 UTC, darlp5589 commented on src/app/pages/dashboard/network-config/networks/networks.component.ts
> +			//if($event.hasOwnProperty('modulation')) this.channelChangedHandler($event);
done

2022-05-05 07:19 UTC, darlp5589 commented
@chriscodev , kindly recheck these concerns you sent above. For the service concern, it's not under my ticket scope yet but I will consider that in the future. For the comments and console.logs, I removed some and retained some since they are very crucial on my implementation especially for data passing between components.

In this new commit, kindly check below scenario:
Select "Update" on a server-existing Logical Network -> Update an Existing ATSC Channel → Make modifications → Ok

Just some notes: I haven't implemented the scenario wherein you add a new network, add some channels on that network and include the network in the network data table and edit that newly added network's set of channels. It will be on a new ticket.

2022-05-13 04:05 UTC, chriscodev reviewed
![atscneterr](https://user-images.githubusercontent.com/68254582/168209078-0e90df0b-f430-454b-92cf-259676bda87a.jpg)
![atscneterr2](https://user-images.githubusercontent.com/68254582/168209082-c1cd9906-f5f6-4fc5-a39d-253bf5077a19.jpg)  

image1 - datatable initialisation error
image2 - select country is available and yet checkmark is greyed out and ok button is disabled

2022-05-16 03:44 UTC, chriscodev approved these changes
This is approve on my end

2022-05-19 21:58 UTC, triveni-codev commented
Merging to master. Implementation structure confirmed for the most part. Kindly take matter on the temporarily replaced implementation of the timezone portion. The timezone has to have the original search function.


~~~~~~
1.Networks Section Development: Accommodation of "Update ATSC Channel" use cases
https://app.asana.com/0/1202172889691467/1202187061972897/f

2.Networks Section Development: Newly added Logical Network(locally dirty all throughout) -> Update existing ATSC Channel 
https://app.asana.com/0/1201468220173184/1202210153506903/f

3.Networks Section - ATSC Channel continuous development: Complete funneling of Added/Updated changes down to the root
https://app.asana.com/0/1202172889691467/1202249852885595/f

2022-05-19 21:58 UTC, merged