Darlp networks 1202309411800128
triveni-codev/GBWebApp-dev pull request #432
Opened 2022-05-25 22:14 UTC by darlp5589

ASANA Ticket source: https://app.asana.com/0/1201943683850147/1202309411800128

@chriscodev , kindly review this PR. This push commit is limited only for BIG COMMIT "added" array features below:
-newly added network (or set of networks)
-newly added network (or set of networks) with one or more channels
-newly added network (or set of networks) with one or more channels with or without transport links
-auto-refresh after network to latest set of networks after commit

Big COMMIT for "updated" array will be in the next push commit.

2022-05-26 22:16 UTC, chriscodev requested changes
- adding atsc chanel model title is edit
- change input field layout to be consistent with other input fields
- 
- ![Screenshot 2022-05-26 220310](https://user-images.githubusercontent.com/68254582/170588536-191323f8-bd12-46fe-8447-c80d9dbd415b.png)

- ![change input field layouts](https://user-images.githubusercontent.com/68254582/170588543-453200a3-b81c-40c2-aa3e-89c5115cb981.png)

2022-05-31 22:46 UTC, chriscodev reviewed
This is approve commit: https://github.com/triveni-codev/GBWebApp-dev/pull/432/commits/053a69fc3958b667c3beccd515031eab4011f031

to note: implementations are commented out or put as hidden for now, please know that this PR is currently under development and that I need those implementation as I currently working on some features included in the scope of this ticket.

2022-06-01 23:41 UTC, chriscodev reviewed
hi Darl , here are my review comments:
- to be same layout as modulation select tag
-  to add default value 'Select Timezone' placeholder same in client app
-  same width with linked transport
- add placeholder to link transport same in client app
![atsc](https://user-images.githubusercontent.com/68254582/171518962-73a6b25a-e57c-4abc-bc34-70794f6d79cf.jpg)

2022-06-05 23:20 UTC, chriscodev commented
hi @darlp5589 , 

COMMIT : https://github.com/triveni-codev/GBWebApp-dev/pull/432/commits/6fe0ac61cf90f2a356fb6cf6a46d653303a3a2c5

approve on my end.

Cheers,
Christian

2022-06-08 00:10 UTC, chriscodev reviewed
not used, we can remove lines codes.

2022-06-08 00:10 UTC, chriscodev commented on src/app/_helpers/idClientIdParam.ts
> +import { min } from "moment";
not used, we can remove this one.

2022-06-08 00:25 UTC, darlp5589 commented on src/app/_helpers/idClientIdParam.ts
> +import { min } from "moment";
Oh yeah! Makes sense! Will do.

2022-06-13 01:31 UTC, chriscodev commented
hi @darlp5589 ,

heres my review comment

when adding data then edit ,clientid should be used on add-editing, cause this will get the data of previous data of id, causing to display invalid data

![bug2](https://user-images.githubusercontent.com/68254582/173263740-0c425cd7-4eae-4b01-b223-db925062b11a.png)

2022-06-13 03:46 UTC, darlp5589 commented
Hi @chriscodev , kindly leave this as is. This was Don's implementation for data-passing purposes (I make use of it so I will have few edits to make on his previous implementation) but if you look on the set of objects, there's an associated clientID which is what I am using for the big commit api request.

2022-06-14 00:51 UTC, triveni-codev commented
Post-discussion w/ Christian and Darl via call was carried out.
Resolution: Code will be updated to consider the fundamental scenario

Fundamental scenario to consider (in relation to the image in https://github.com/triveni-codev/GBWebApp-dev/pull/432#issuecomment-1153363188)
Reviewer:  Christian
Topic: clashing of information of a newly added id 33 vs an existing id 33
1. Current id info from server for example :39 and 33
2. Added new Transports until id 33 is reached
3. Click on a server-existing Transport row to update(presumably id 33 from server)
Actual result: name from client side is viewed
Expected result: name/info from server should be viewed in the modal
~~~~~~~~~~~
Client id val: Date time value down to millisecond (edited)

2022-06-15 00:26 UTC, chriscodev approved these changes
LGTM

2022-06-15 00:41 UTC, darlp5589 commented on src/app/pages/dashboard/network-config/networks/networks.component.ts
> +							if(dataRow === undefined) {
Gotcha!

2022-06-29 01:11 UTC, triveni-codev commented
Scoped out and reviewed by Christian. Merging this PR. I may have newfound "dynamics" concern leading up to succeeding PRs. previous prevailing concern on the modified  "min.scss" under eliteadmin assets folder has been addressed and sorted out.

2022-06-29 01:11 UTC, merged