Darlp networks atsc cable virtual channel 1203486985241019
triveni-codev/GBWebApp-dev pull request #516
Opened 2022-12-07 07:49 UTC by darlp5589

Hi @triveni-codev , @chriscodev , @pauljustinhernandez 

Kindly check this PR ONLY FOR DIRTY CHANGE and RETRIEVAL/DISPLAY FROM SERVER on both add and update functionalities ONLY FOR ATSC CABLE. 

DON'T Test the Big Commit yet.

2 ASANA Tickets associated: 
ASANA: https://app.asana.com/0/1201943683850147/1203486985241019
ASANA: https://app.asana.com/0/1201943683850147/1203486985241021

To test: 
-Virtual Channel should consider the following: 
>1 to 16383 as Major only (no Minor value) is acceptable
>999-999 as biggest Major-Minor value is acceptable
>0-(1 to 999) as Major-Minor values are acceptable
>(1 to 999)-0 as Major Minor values are acceptable
>(1 to 999)-(1 to 999) Major-Minor value combinations are acceptable

Notes:
0 is not acceptable as Major only value
0-0 is not acceptable as Major-Minor value

Please also test the PATH SELECT and OUT OF BAND checkboxes and make sure they are working.

2022-12-09 16:14 UTC, pauljustinhernandez commented
Hi Darl @darlp5589 , sending here some issues encountered during testing;
1. **0-(1 to 999) as Major-Minor values are acceptable**  ~ As a user I need to press and hold the zero(0) key before I can input dash and minor values.
![bug2-need to hold zero](https://user-images.githubusercontent.com/105896213/206743886-e39f7567-e346-44df-b019-2da4798b1c9f.gif)

2. **0-(1 to 999) as Major-Minor values are acceptable** ~ greater than 999 (minor value) is accepted when the user press and hold the nine(9) key and move to the other input fields immediately.
![bug3-9999 accepted](https://user-images.githubusercontent.com/105896213/206744857-47defa08-8a8c-49d0-9627-c1bf15cedee7.gif)

2022-12-09 23:58 UTC, darlp5589 commented
Hi @pauljustinhernandez ,

1. 0-(1 to 999) as Major-Minor values are acceptable ~ As a user I need to press and hold the zero(0) key before I can input dash and minor values.
[PLEASE DISREGARD. THIS IS EXACTLY THE SAME BEHAVIOR WITH JAVA APP. IT IS HIGHLY DISCOURAGED TO HAVE 0-(1 to 999) BUT SHOULD BE ACCEPTED IF INTENTIONALLY INPUTTED. YOU CAN ALSO INPUT LIKE 1-999 THEN MANUALLY CHANGE 1 TO 0, THAT IS ACCEPTED IN JAVA APP BUT INTENTIONALLY TYPING 0 FIRST WON'T ALLOW BASED ON THE IMPLEMENTATION]

2. 0-(1 to 999) as Major-Minor values are acceptable ~ greater than 999 (minor value) is accepted when the user press and hold the nine(9) key and move to the other input fields immediately.
[ALREADY FIXED]

2022-12-12 06:16 UTC, pauljustinhernandez requested changes
Hi Darl @darlp5589 LGTM, I just have comments on your codes before I'll approve on this, mainly~ 
- optional chaining
- commented codes

2022-12-12 06:16 UTC, pauljustinhernandez commented on src/app/_helpers/alphaNumericValidator.ts
> +    if (!num.toString()?.includes('-') && (val < 1 || val > majorLimit)) {
?.toString()

2022-12-12 06:16 UTC, pauljustinhernandez commented on src/app/pages/main/network-config/networks/modal-networks/modal-networks-atsc-service/modal-networks-atsc-service.component.ts
> +        if( this.serviceDataObject.virtual.toString().includes('-')) {
optional chaining

2022-12-12 06:16 UTC, pauljustinhernandez commented on src/app/pages/main/network-config/networks/modal-networks/modal-networks-atsc-service/modal-networks-atsc-service.component.ts
> +        if( this.serviceDataObject.virtual.toString().includes('-')) {
optional chaining

2022-12-12 07:33 UTC, darlp5589 commented on src/app/_helpers/alphaNumericValidator.ts
> +    if (!num.toString()?.includes('-') && (val < 1 || val > majorLimit)) {
Resolved

2022-12-12 07:34 UTC, darlp5589 commented on src/app/pages/main/network-config/networks/modal-networks/modal-networks-atsc-service/modal-networks-atsc-service.component.ts
> +        if( this.serviceDataObject.virtual.toString().includes('-')) {
Resolved.

2022-12-12 07:35 UTC, darlp5589 commented on src/app/pages/main/network-config/networks/modal-networks/modal-networks-atsc-service/modal-networks-atsc-service.component.ts
> +        if( this.serviceDataObject.virtual.toString().includes('-')) {
Resolved.

2022-12-12 08:44 UTC, pauljustinhernandez requested changes
Additonal review Darl, regarding the above latest comment

2022-12-12 08:44 UTC, pauljustinhernandez commented on src/app/pages/main/network-config/networks/networks.component.ts
>  		// 				if(serviceItem.description === undefined) serviceObject['description'] = "";
commented codes; remove if necessary

2022-12-12 08:44 UTC, pauljustinhernandez commented on src/app/pages/main/network-config/networks/modal-networks/modal-networks-atsc-service/modal-networks-atsc-service.component.ts
> +          if(inputKey.toString().includes('-') && inputKey[inputKeyLen-2] != '-') {
optional chaining

2022-12-12 08:44 UTC, pauljustinhernandez commented on src/app/pages/main/network-config/networks/modal-networks/modal-networks-atsc-service/modal-networks-atsc-service.component.ts
> +          if( inputKey.toString().includes('-')) {
optional chaining

2022-12-12 08:44 UTC, pauljustinhernandez commented on src/app/pages/main/network-config/networks/modal-networks/modal-networks-atsc-service/modal-networks-atsc-service.component.ts
> +          else if(inputKey.toString().includes('-') && event.key != '-') this.isValid = true;
optional chaining

2022-12-12 08:44 UTC, pauljustinhernandez commented on src/app/pages/main/network-config/networks/modal-networks/modal-networks-atsc-service/modal-networks-atsc-service.component.ts
>              if(this.serviceDataObject.virtual.split('-')[1]?.length > 0) this.isValid = true;
optional chaining

2022-12-12 08:44 UTC, pauljustinhernandez commented on src/app/pages/main/network-config/networks/modal-networks/modal-networks-atsc-service/modal-networks-atsc-service.component.ts
> +        if( this.serviceDataObject.virtual.toString().includes('-')) {
optional chaining

2022-12-12 08:44 UTC, pauljustinhernandez commented on src/app/pages/main/network-config/networks/modal-networks/modal-networks-atsc-service/modal-networks-atsc-service.component.ts
>              num = inputKey.split('-');
optional chaining

2022-12-12 08:44 UTC, pauljustinhernandez commented on src/app/pages/main/network-config/networks/modal-networks/modal-networks-atsc-service/modal-networks-atsc-service.component.ts
> +            minor = minor.substring(0,3);
optional chaining

2022-12-12 08:44 UTC, pauljustinhernandez commented on src/app/pages/main/network-config/networks/modal-networks/modal-networks-atsc-service/modal-networks-atsc-service.component.ts
> +            major = major.substring(0,3);
optional chaining

2022-12-12 08:44 UTC, pauljustinhernandez commented on src/app/pages/main/network-config/networks/modal-networks/modal-networks-atsc-service/modal-networks-atsc-service.component.ts
> +          let num = this.serviceDataObject.virtual.split('-');
optional chaining

2022-12-12 08:44 UTC, pauljustinhernandez commented on src/app/pages/main/network-config/networks/modal-networks/modal-networks-atsc-service/modal-networks-atsc-service.component.ts
> +        if( this.serviceDataObject.virtual?.toString().includes('-')) {
optional chaining

2022-12-12 08:44 UTC, pauljustinhernandez commented on src/app/pages/main/network-config/networks/modal-networks/modal-networks-atsc-service/modal-networks-atsc-service.component.ts
>            num = this.serviceDataObject.virtual.split('-');
optional chaining

2022-12-12 08:44 UTC, pauljustinhernandez commented on src/app/pages/main/network-config/networks/modal-networks/modal-networks-atsc-service/modal-networks-atsc-service.component.ts
> +        if( this.serviceDataObject.virtual?.toString().includes('-')) {
optional chaining

2022-12-12 09:58 UTC, darlp5589 commented on src/app/pages/main/network-config/networks/modal-networks/modal-networks-atsc-service/modal-networks-atsc-service.component.ts
> +        if( this.serviceDataObject.virtual?.toString().includes('-')) {
resolved

2022-12-12 09:58 UTC, darlp5589 commented on src/app/pages/main/network-config/networks/modal-networks/modal-networks-atsc-service/modal-networks-atsc-service.component.ts
>            num = this.serviceDataObject.virtual.split('-');
resolved

2022-12-12 09:59 UTC, darlp5589 commented on src/app/pages/main/network-config/networks/modal-networks/modal-networks-atsc-service/modal-networks-atsc-service.component.ts
> +          let num = this.serviceDataObject.virtual.split('-');
resolved

2022-12-12 10:01 UTC, darlp5589 commented on src/app/pages/main/network-config/networks/modal-networks/modal-networks-atsc-service/modal-networks-atsc-service.component.ts
>              if(this.serviceDataObject.virtual.split('-')[1]?.length > 0) this.isValid = true;
resolved

2022-12-12 10:02 UTC, darlp5589 commented on src/app/pages/main/network-config/networks/modal-networks/modal-networks-atsc-service/modal-networks-atsc-service.component.ts
> +          else if(inputKey.toString().includes('-') && event.key != '-') this.isValid = true;
resolved

2022-12-12 10:03 UTC, darlp5589 commented on src/app/pages/main/network-config/networks/modal-networks/modal-networks-atsc-service/modal-networks-atsc-service.component.ts
> +          if( inputKey.toString().includes('-')) {
resolved

2022-12-12 10:03 UTC, darlp5589 commented on src/app/pages/main/network-config/networks/modal-networks/modal-networks-atsc-service/modal-networks-atsc-service.component.ts
> +          if(inputKey.toString().includes('-') && inputKey[inputKeyLen-2] != '-') {
resolved

2022-12-12 10:05 UTC, darlp5589 commented on src/app/pages/main/network-config/networks/networks.component.ts
>  		// 				if(serviceItem.description === undefined) serviceObject['description'] = "";
I am using these entire set of big commit codes time to time on all my PRs. I will remove these in the future.

2022-12-12 10:06 UTC, darlp5589 commented
Hi @pauljustinhernandez done resolving. You may recheck on them. Thanks!

2022-12-12 13:43 UTC, pauljustinhernandez commented
Hi Darl @darlp5589 conducted a final testing for this PR. I encountered an issue ~ see below

1. **1 to 16383 as Major only (no Minor value) is acceptable** ~ greater than 16383 (major only value) is accepted when the user press and hold a desired number key and move to the other input fields immediately. In this example, I input 1638 and press and hold 5.
![image](https://user-images.githubusercontent.com/105896213/207059073-51bb9c2e-deb3-4171-be1f-369532aad48c.png)

2022-12-13 01:59 UTC, darlp5589 commented
@pauljustinhernandez , done fixing this concern. You may verify. Thanks!

2022-12-13 11:00 UTC, pauljustinhernandez commented
LGTM Darl! @darlp5589

2023-01-02 21:40 UTC, merged